In [1]:
from typing import Tuple
from tqdm import tqdm
from sklearn.model_selection import train_test_split
import pandas as pd

import numpy as np

import torch

from torch import nn
from torch.utils.data import Dataset, DataLoader

from catboost import CatBoostClassifier, MultiTargetCustomMetric

import wandb

In [2]:
# df = pd.concat([pd.read_csv("more-elements/more-elements.csv"), pd.read_csv("new-more-data/new-more-data.csv")])
# df
df = pd.read_pickle("half_data.pkl")
df

0             1             2             3             4  \
0       1.402026e-21  1.650584e-21  1.910661e-21  2.264304e-21  2.829955e-21   
1       4.102767e-22  4.371429e-22  4.698476e-22  5.105580e-22  5.626400e-22   
2       3.610634e-23  2.739156e-23  1.628379e-23  1.195799e-23  1.069667e-23   
3       1.016487e-22  1.356304e-22  1.894228e-22  3.406116e-22  8.410447e-22   
4       1.637227e-21  2.113385e-21  2.633061e-21  3.098701e-21  3.509187e-21   
...              ...           ...           ...           ...           ...   
183548  1.720379e-22  2.933964e-22  4.190668e-22  5.128756e-22  6.537258e-22   
183549  2.392508e-21  1.998411e-21  1.320957e-21  9.131813e-22  6.948151e-22   
183550  1.947286e-22  2.092204e-22  2.261748e-22  2.462494e-22  2.703056e-22   
183551  4.523992e-22  6.372981e-22  1.661855e-21  1.874233e-22  1.226359e-22   
183552  4.111637e-21  9.719901e-21  4.291975e-21  1.383255e-22  9.272536e-23   

                   5             6             7             8             9  \
0       3.673546e-21  4.745899e-21  5.773241e-21  6.446840e-21  6.741727e-21   
1       6.315813e-22  7.266133e-22  8.610945e-22  1.048941e-21  1.323529e-21   
2       1.058083e-23  1.121691e-23  1.274356e-23  1.515703e-23  1.882304e-23   
3       2.039525e-21  1.635235e-21  6.587985e-22  3.087047e-22  2.124933e-22   
4       3.569827e-21  3.557713e-21  3.356628e-21  3.389955e-21  3.744591e-21   
...              ...           ...           ...           ...           ...   
183548  6.598291e-22  7.231058e-22  6.818061e-22  8.002978e-22  1.130003e-21   
183549  5.720024e-22  4.987314e-22  4.533583e-22  4.270046e-22  4.143369e-22   
183550  2.995569e-22  3.357735e-22  3.814871e-22  4.405433e-22  5.189812e-22   
183551  1.804612e-22  3.107570e-22  1.559673e-21  3.250324e-21  2.427107e-21   
183552  5.006519e-22  7.290239e-22  1.258661e-21  2.270487e-21  4.044166e-21   

        ...          1000  element_1  element_2  element_3  element_1_ratio  \
0       ...  3.466256e-20         17         23         -1         0.440157   
1       ...  2.481710e-21          0         19         -1         0.428047   
2       ...  2.756785e-21          2         11         13         0.342547   
3       ...  1.240249e-22          6         10         13         0.053299   
4       ...  3.614986e-23          9         18         24         0.470739   
...     ...           ...        ...        ...        ...              ...   
183548  ...  8.585612e-23          9         17         23         0.401527   
183549  ...  2.460996e-21          4          8         16         0.348675   
183550  ...  1.838447e-23          1          7         14         0.116401   
183551  ...  1.508687e-21         15         18         23         0.422131   
183552  ...  1.719644e-21          3         12         23         0.425460   

        element_2_ratio  element_3_ratio   temp  pressure  air_ratio  
0              0.559843         0.000000  283.0     0.775        0.0  
1              0.571953         0.000000  303.0     0.800        0.6  
2              0.376666         0.280788  283.0     0.500        0.6  
3              0.321178         0.625524  293.0     0.900        0.6  
4              0.251465         0.277796  273.0     0.500        0.6  
...                 ...              ...    ...       ...        ...  
183548         0.454117         0.144356  313.0     0.500        0.6  
183549         0.389984         0.261341  323.0     1.000        0.6  
183550         0.430989         0.452610  313.0     0.100        0.6  
183551         0.441890         0.135979  283.0     0.200        0.3  
183552         0.037319         0.537220  273.0     0.100        0.6  

[183553 rows x 1010 columns]

In [3]:
print(len(df))
df = df[(df[[str(i) for i in range(1001)]] > 0).all(axis=1)]
print(len(df))

183553
183553


In [4]:
len(df[(df["element_1"] == 0) | (df["element_2"] == 0) | (df["element_3"] == 0)]) / len(df)

0.11451733286843582

In [3]:
class CustomCatboostSpectraDataset(Dataset):
    def __init__(self, data: pd.DataFrame, device="cuda:0") -> None:
        self.data = data
        self.elements = self.data["element_1"].unique()
        self.air_ratios = data.air_ratio.to_numpy(dtype=np.float64)

        self.spectras = self.data[[str(i) for i in range(1001)]].to_numpy(
            dtype=np.float64
        )

        self.ratios = self.data[
            ["element_1_ratio", "element_2_ratio", "element_3_ratio"]
        ].to_numpy(dtype=np.float64)
        self.element_indices = self.data[
            ["element_1", "element_2", "element_3"]
        ].to_numpy(dtype=np.int32)

    def __len__(self) -> int:
        return len(self.data)

    def __getitem__(self, idx: int) -> Tuple[np.ndarray, np.ndarray]:
        spectra = np.log(self.spectras[idx])

        elements_distribution = np.zeros(
            [len(self.elements) + 1], dtype=np.float64
        )
        indices = self.element_indices[idx, :]
        indices = indices[indices != -1]
        elements_distribution[indices] = self.ratios[idx][
                    range(indices.shape[0])
        ] * (1 - self.air_ratios[idx])
        elements_distribution[-1] = self.air_ratios[idx]

        return spectra, elements_distribution

In [4]:
train_df, val_df = train_test_split(df, test_size=0.15, random_state=42)

In [5]:
train_dataset = CustomCatboostSpectraDataset(train_df, device="cpu")
val_dataset = CustomCatboostSpectraDataset(val_df, device="cpu")

In [6]:
X_train, y_train = np.array([train_dataset[i][0] for i in range(len(train_dataset))]), np.array(
    [train_dataset[i][1] for i in range(len(train_dataset))]
)

X_val, y_val = np.array([val_dataset[i][0] for i in range(len(val_dataset))]), np.array(
    [val_dataset[i][1] for i in range(len(val_dataset))]
)

In [7]:
def cross_entropy(predictions, targets, epsilon=1e-12):
    """
    Computes cross entropy between targets (encoded as one-hot vectors)
    and predictions.
    Input: predictions (N, k) ndarray
           targets (N, k) ndarray
    Returns: scalar
    """
    predictions = np.clip(predictions, epsilon, 1.0 - epsilon)
    N = predictions.shape[0]
    ce = -np.sum(targets * np.log(predictions + 1e-9)) / N
    return ce

In [8]:
class CEMetric(MultiTargetCustomMetric):

    @staticmethod
    def get_cross_entropy(y_true, y_pred):
        return cross_entropy(y_pred, y_true)

    def is_max_optimal(self):
        return False  # smaller is better

    def evaluate(self, approxes, target, weight):
        assert len(approxes) == 1
        assert len(target) == len(approxes[0])
        y_true = np.array(target).astype(int)
        approx = approxes[0]
        score = self.get_cross_entropy(y_true, approx)
        return score, 1

    def get_final_error(self, error, weight):
        return error

In [20]:
gb = CatBoostClassifier(
    task_type="GPU",
    learning_rate=0.5,
    bootstrap_type="No",
    l2_leaf_reg=100,
    loss_function="MultiCrossEntropy",
)
gb.fit(X=X_train, y=y_train, eval_set=(X_val, y_val), plot=True)

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.1857314	test: 0.1857022	best: 0.1857022 (0)	total: 422ms	remaining: 7m 1s
1:	learn: 0.1245529	test: 0.1245203	best: 0.1245203 (1)	total: 705ms	remaining: 5m 51s
2:	learn: 0.1099288	test: 0.1098220	best: 0.1098220 (2)	total: 968ms	remaining: 5m 21s
3:	learn: 0.1037227	test: 0.1036489	best: 0.1036489 (3)	total: 1.23s	remaining: 5m 5s
4:	learn: 0.0995366	test: 0.0994384	best: 0.0994384 (4)	total: 1.49s	remaining: 4m 57s
5:	learn: 0.0962807	test: 0.0961859	best: 0.0961859 (5)	total: 1.76s	remaining: 4m 51s
6:	learn: 0.0948650	test: 0.0947641	best: 0.0947641 (6)	total: 2s	remaining: 4m 44s
7:	learn: 0.0934959	test: 0.0934020	best: 0.0934020 (7)	total: 2.24s	remaining: 4m 37s
8:	learn: 0.0918729	test: 0.0917717	best: 0.0917717 (8)	total: 2.51s	remaining: 4m 36s
9:	learn: 0.0906945	test: 0.0906046	best: 0.0906046 (9)	total: 2.77s	remaining: 4m 33s
10:	learn: 0.0897455	test: 0.0896482	best: 0.0896482 (10)	total: 3.03s	remaining: 4m 32s
11:	learn: 0.0892409	test: 0.0891532	best: 0.0

In [10]:
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    precision_score,
    recall_score,
    mean_absolute_error,
    f1_score,
)

In [21]:
# task_type="GPU",
# learning_rate=0.5,
# bootstrap_type="No",
# l2_leaf_reg=100,
# loss_function="MultiCrossEntropy",

pred = gb.predict_proba(X_val)
print(f"CE: {cross_entropy(pred, y_val)}")
print(f"MAE: {mean_absolute_error(pred, y_val)}")

CE: 1.1958940831917138
MAE: 0.011946761724214671


In [17]:
# task_type="GPU",
# learning_rate=0.5,
# l2_leaf_reg=100,
# loss_function="MultiCrossEntropy",

pred = gb.predict_proba(X_val)

print(f"CE: {cross_entropy(pred, y_val)}")
print(f"MAE: {mean_absolute_error(pred, y_val)}")

CE: 1.2010123221500588
MAE: 0.012266067302315652


In [19]:
# task_type="GPU",
# learning_rate=0.5,
# l2_leaf_reg=1000,
# loss_function="MultiCrossEntropy",

pred = gb.predict_proba(X_val)

print(f"CE: {cross_entropy(pred, y_val)}")
print(f"MAE: {mean_absolute_error(pred, y_val)}")

CE: 1.2297390868644482
MAE: 0.013717765207713006


In [17]:
f1_score(y_val, pred, average=None)

array([0.99661345, 0.45485961, 0.48228767, 0.99227251, 0.9924812 ,
       0.99634631, 0.85777207, 0.9419885 , 0.38819474, 0.95733646,
       0.98312784, 0.98862397, 0.9935918 , 0.99094437, 0.99527918,
       0.99440805, 0.99065124, 0.99488655, 0.99694583, 0.99426268,
       0.9831946 , 0.98709163, 0.96382008, 0.99029744, 0.97259608])

In [35]:
pred, y_val[i]

(array([1.23883874e-06, 4.38560582e-03, 5.62113566e-03, 4.34981757e-04,
        1.37915759e-05, 1.60435102e-05, 6.15459019e-03, 5.16426915e-03,
        6.25508849e-03, 3.83966453e-03, 3.68702319e-04, 1.52557320e-04,
        1.44995356e-05, 1.01582786e-04, 1.56701221e-01, 3.78149110e-06,
        2.47053659e-01, 3.95344475e-04, 2.64859709e-04, 2.57998431e-05,
        2.71519559e-03, 2.26385942e-04, 3.70902956e-03, 1.02934236e-04,
        2.68017492e-02, 5.55836556e-01]),
 array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.19726331,
        0.        , 0.39952827, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.10320842,
        0.3       ]))

In [36]:
np.sum(np.abs(pred[y_val[i] != 0] - y_val[i][y_val[i] != 0])) / y_val[i][y_val[i] != 0].shape[0]

0.1313199816354742

In [14]:
pred_total = gb.predict_proba(X_val)

In [15]:
cross_entropy(pred_total, y_val)

1.237707421082145